"""
GitPulse - CLI & Pre-Commit Hook Tool
Allows scanning staged git commits or local files directly from the terminal.
"""

import argparse
import os
import sys
from typing import List

from .scanner import SecretScanner, SecretFinding
from .remediator import SecretRemediator
from .git_utils import get_staged_diff, is_git_repo

# Ensure safe console output across Windows cp1252 / UTF-8
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

def print_banner():
    banner = r"""
===================================================================
   ______ _ _   _____       _           
  / ____/(_) |_|  __ \     | |          
 | |  __  _| __| |__) |   _| |___  ___  
 | | |_ || | |_|  ___/ | | | / __|/ _ \ 
 | |__| || | |_| |   | |_| | \__ \  __/ 
  \_____||_|\__|_|    \__,_|_|___/\___| 
  Git Pre-Commit Secret Interceptor & Auto-Remediator
===================================================================
"""
    print(banner)



def format_finding_cli(finding: SecretFinding) -> str:
    return (
        f"  [!] {finding.rule_name} detected!\n"
        f"      File:     {finding.file_path}:{finding.line_number}\n"
        f"      Entropy:  {finding.entropy:.3f} (Threshold: {finding.threshold:.2f}, Level: {finding.entropy_level})\n"
        f"      Secret:   {finding.masked_value}\n"
        f"      Snippet:  {finding.line_content}\n"
        f"      Remedy:   Use env var {finding.suggested_env_var}\n"
    )


def scan_staged_commits() -> int:
    """
    Scans staged Git diff. If secrets are found, exits with status 1 to abort commit.
    """
    if not is_git_repo("."):
        print("[GitPulse] Warning: Current directory is not a Git repository.")
        return 0

    success, diff_text = get_staged_diff(".")
    if not success or not diff_text.strip():
        # No staged changes
        return 0

    scanner = SecretScanner()
    findings = scanner.scan_git_diff(diff_text)

    if not findings:
        print("[GitPulse] [OK] No secrets detected in staged changes. Commit clean!")
        return 0

    print_banner()
    print(f"\033[91m[GitPulse ALERT] Intercepted {len(findings)} hardcoded secret(s) in staged commit!\033[0m\n")
    for f in findings:
        print(format_finding_cli(f))

    print("\033[93m[Action Required] Please remove or remediate these secrets before committing.\033[0m")
    print("Tip: Run 'streamlit run app.py' to visually inspect and auto-remediate with 1 click!\n")
    return 1


def install_pre_commit_hook():
    """Installs pre-commit hook into .git/hooks/pre-commit."""
    if not os.path.exists(".git"):
        print("[GitPulse] Error: No .git directory found in current directory.")
        return 1

    hooks_dir = os.path.join(".git", "hooks")
    os.makedirs(hooks_dir, exist_ok=True)
    hook_path = os.path.join(hooks_dir, "pre-commit")

    hook_script = """#!/bin/sh
# GitPulse Pre-Commit Secret Interceptor Hook
# Auto-generated by GitPulse

echo "🔍 Running GitPulse secret scan on staged changes..."

# Prefer py on Windows if available, otherwise python3/python
if command -v py >/dev/null 2>&1; then
    py -m gitpulse.cli --staged
elif command -v python3 >/dev/null 2>&1; then
    python3 -m gitpulse.cli --staged
else
    python -m gitpulse.cli --staged
fi

RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "❌ GitPulse: Commit blocked due to detected secrets."
    exit 1
fi

echo "✅ GitPulse: Secret scan passed."
exit 0
"""
    with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(hook_script)

    try:
        os.chmod(hook_path, 0o755)
    except Exception:
        pass

    print(f"[GitPulse] Pre-commit hook successfully installed at: {hook_path}")
    return 0


def main():
    parser = argparse.ArgumentParser(description="GitPulse: Git Pre-Commit Secret Interceptor & Auto-Remediator")
    parser.add_argument("--staged", action="store_true", help="Scan staged git diff (used by pre-commit hook)")
    parser.add_argument("--scan-file", type=str, help="Scan a specific source file or diff file")
    parser.add_argument("--remediate", type=str, help="Remediate secrets in a file and generate patch")
    parser.add_argument("--output", type=str, help="Output path for remediated file")
    parser.add_argument("--patch-out", type=str, help="Output path for generated .patch file")
    parser.add_argument("--install-hook", action="store_true", help="Install GitPulse as local git pre-commit hook")

    args = parser.parse_args()

    if args.install_hook:
        sys.exit(install_pre_commit_hook())

    if args.staged:
        sys.exit(scan_staged_commits())

    if args.scan_file:
        if not os.path.exists(args.scan_file):
            print(f"[GitPulse] Error: File '{args.scan_file}' not found.")
            sys.exit(1)
            
        with open(args.scan_file, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()

        scanner = SecretScanner()
        if args.scan_file.endswith(".diff") or args.scan_file.endswith(".patch"):
            findings = scanner.scan_git_diff(content)
        else:
            findings = scanner.scan_content(content, file_path=args.scan_file)

        print_banner()
        if not findings:
            print(f"[GitPulse] [OK] Clean! No secrets detected in {args.scan_file}")
            sys.exit(0)
        else:
            print(f"[GitPulse] Found {len(findings)} secret(s) in {args.scan_file}:\n")
            for f in findings:
                print(format_finding_cli(f))
            sys.exit(1)

    if args.remediate:
        if not os.path.exists(args.remediate):
            print(f"[GitPulse] Error: File '{args.remediate}' not found.")
            sys.exit(1)
            
        with open(args.remediate, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()

        scanner = SecretScanner()
        findings = scanner.scan_content(content, file_path=args.remediate)

        if not findings:
            print(f"[GitPulse] No secrets detected in {args.remediate}. No remediation needed.")
            sys.exit(0)

        remediator = SecretRemediator()
        sanitized, patch, env_ex = remediator.remediate_content(content, findings, file_path=args.remediate)

        print(f"[GitPulse] Remediated {len(findings)} secrets successfully!")
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(sanitized)
            print(f"  -> Remediated code written to: {args.output}")

        if args.patch_out:
            with open(args.patch_out, "w", encoding="utf-8") as f:
                f.write(patch)
            print(f"  -> Unified patch written to: {args.patch_out}")

        print("\nGenerated .env.example:")
        print(env_ex)
        sys.exit(0)

    # Default: Show help
    parser.print_help()


if __name__ == "__main__":
    main()
